name: Node CI-workflow

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  CI-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6  
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
      - name: Install dependencies
        run: npm ci
      - name: Audit
        run: npm audit --audit-level="high"
      - name: Linting
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build

  Docker-publish:
    needs: CI-workflow
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ci-trainings
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
